### ISSUE TITLE
Seeed Wio LTE M1 / NB1 (BG96) board installation error

### ISSUE THREAD

**Issue by jr2cch** [SeeedJP/Arduino_Core_STM32#4]
We become indebted to. My name is Matsuoka from SBKK.
In the environment settings when developing Seeed Wio LTE M1 / NB1 (BG96) with Arduino IDE
When installing the board definition from the board manager
An error will occur at https://azureboard.azureedge.net/toolchain/openocd-0.10.0-32zip.
It seems that the https://azureboard.azureedge.net site is down.
I would appreciate it if you could teach me how to deal with it.

**Comment by matsujirushi** [comment]
Hi @jr2cch ,
Thanks for this report.
You are right, no response from azureboard.azureedge.net.
I think it is hosted by Microsoft's VSChina team. I ask them.
Please take a moment.

[ERROR: cannot download openocd-0.10.0-32.zip@stackoverflow](https://stackoverflow.com/questions/65320410/error-cannot-download-openocd-0-10-0-32-zip)

**Comment by matsujirushi** [comment]
Hi @jr2cch ,
We changed the download server.
Please update the platform to 1.5.0.

![image](https://user-images.githubusercontent.com/8079404/102452577-e9a61f00-407d-11eb-9666-c3d47f9997b4.png)

**Comment by jr2cch** [comment]
We become indebted to.
I'm still getting the following error.
I will attach an image.
![Seeed_STM32F4Board](https://user-images.githubusercontent.com/76098856/102457859-c16eee00-4086-11eb-810e-10f1ff78cc3d.png)

**Comment by matsujirushi** [comment]
Hi @jr2cch ,
We will not maintain `SeeedJP STM32F4 Boards`.
`SeeedJP STM32F4 Boards` is **DEPRECATED**.
Please migrate your project to `SeeedJP STM32 Boards`.

**Comment by jr2cch** [comment]
We become indebted to.
Thank you for your reply.
I understand that the device is not supported.
Try changing the device.
Thank you very much.

**Comment by matsujirushi** [comment]
Fixed the `SeeedJP STM32F4 Boards`(**DEPRECATED**).
