### ISSUE TITLE
Wio3GのI2Cスレーブ使用時のハングアップについて

### ISSUE THREAD

**Issue by snippet2021** [SeeedJP/Arduino_Core_STM32#6]
# 概要
Wio3G(STM32F439VI)を使用しています．
I2Cの受信時に，マイコン全体の動作が停止するので調査をお願いします．

# 再現手順　
ESP32-WROOM-32（Master）とWIO3G(slave)を，I2Cで接続．

**ボード(Arduino IDE)**
esp32 by Espressif Systems  - 2.0.3
SeedJP STM32 Boards by Seed.K.K - 1.8.0

**（ライブラリ）**
WioCellLibforArduino -1.7.0

以下のプログラムを実行する，

**ESP32-WROOM-32（Master）**
```
#include <Wire.h>

#define I2C_ADDR  2

byte x = 0;

void setup()
{
  Wire.begin();        // join i2c bus (address optional for master)
  Serial.begin(9600);  // start serial for output
}

void loop()
{
//  Serial.println(11111);
//  Wire.requestFrom(I2C_ADDR, 6);  // request 6 bytes from slave device
//
//  while(Wire.available())         // slave may send less than requested
//  {
//    char c = Wire.read();         // receive a byte as character
//    Serial.print(c);              // print the character
//  }
//  Serial.println();
  delay(10);

  Wire.beginTransmission(I2C_ADDR); // transmit to device
  Wire.write("x is ");              // sends five bytes
  Wire.write(x);                    // sends one byte
  Wire.endTransmission();           // stop transmitting
  x++;

  delay(500);
}
```

**WIO3G(slave)**
```
#include <WioCellLibforArduino.h> 

#define I2C_ADDR  2

void setup()
{
  Wire.begin(I2C_ADDR);         // join i2c bus with address SeeedJP/SeeedJP_STM32F4#4
  Wire.onRequest(requestEvent); // register event
  Wire.onReceive(receiveEvent); // register event
  SerialUSB.begin(9600);           // start serial for output
}

void loop()
{
  delay(90);
  SerialUSB.println(111111);  
}

// function that executes whenever data is received from master
// this function is registered as an event, see setup()
void receiveEvent(int howMany)
{
  while(1 < Wire.available()) // loop through all but the last
  {
    char c = Wire.read();     // receive byte as a character
   SerialUSB.printf("%c",c);          // print the character
  }
  int x = Wire.read();        // receive byte as an integer
  SerialUSB.printf("%d\n",x);        // print the integer
}
//
// function that executes whenever data is requested by master
// this function is registered as an event, see setup()
void requestEvent()
{
  delay(50);
  Wire.write("hello\n");  // respond with message of 6 bytes
                          // as expected by master
}
```

# その他
slaveのloop内のdelayを小さくすると止まりやすくなります，
止まる瞬間は，receiveEvent()コールバックが呼び出される前であり，その後Loopにも処理が返ってこないため，I2Cを受信した際の割り込みのライブラリ内でハングアップしてると考えています．
止まっている時のI2Cの波形を確認したところ，masterはアドレスを送信するものの，slaveがAckを返さないというところまでは確認できました．
なお，このコードでは確認していませんが，別のコードでI2C通信を行なっている時USBserial出力を全て消しても数日-数週間後には停止しました．

逆に，masterのコメントアウトを外してrequestFromだけを送信する場合は，確認した限りでは停止していません．（タイミングの問題かもしれません）

**Comment by matsujirushi** [comment]
`receiveEvent()`と`requestEvent()`は割り込みハンドラから呼び出される関数なので、呼び出せる関数に制約があります。
`delay()`は、割り込みハンドラ内の待機になるので使うべきではありません。また、`SerialUSB`は（詳細な実装までは確認していませんが）割り込みハンドラ内では使えないと思います。

### `receiveEvent()`の呼び出しグラフ

```
receiveEvent()
  onReceiveService()
    HAL_I2C_AddrCallback()
      I2C_Slave_ADDR()
        HAL_I2C_EV_IRQHandler() *
    HAL_I2C_ListenCpltCallback()
      I2C_Slave_STOPF()
        HAL_I2C_EV_IRQHandler() *
      I2C_Slave_AF()
        HAL_I2C_ER_IRQHandler() *
      I2C_ITError()
        HAL_I2C_Master_Abort_IT()
        HAL_I2C_ER_IRQHandler() *
        I2C_Slave_STOPF()
          HAL_I2C_EV_IRQHandler() *
```

```
HAL_I2C_EV_IRQHandler()
  I2C1_EV_IRQHandler() = I2C1_IRQHandler() = 割り込みハンドラ
  I2C2_EV_IRQHandler() = I2C2_IRQHandler() = 割り込みハンドラ
  ...
  2C_ER_IRQHandler()
  I2C1_EV_IRQHandler() = I2C1_IRQHandler() = 割り込みハンドラ
  I2C1_ER_IRQHandler() = I2C2_IRQHandler() = 割り込みハンドラ
  ...
```

### テスト

いただいたサンプルコードを、`delay()`と`SerialUSB`をコメントにしてテストしました。動作しているか否かは、I2Cバスにロジックアナライザ（Saleae Logic）を接続して確認しました。

* I2Cマスター ... Seeed Studio XIAO ESP32C3
* I2Cスレーブ ... Wio 3G

テストの様子：

![image](https://user-images.githubusercontent.com/8079404/222053060-7d9711f5-d688-42c8-989e-bf4b546f2dbe.png)

### テスト結果

昨日2時間、本日4時間動かしましたが、とくに停止することなく動きました。

I2C信号の様子：

![wio3g_issue1](https://user-images.githubusercontent.com/8079404/222053569-18477d95-1294-476c-b26c-1dc4580f6023.png)

I2C信号の波形：

![wio3g_issue2](https://user-images.githubusercontent.com/8079404/222053585-9a846e5c-ed99-4dc4-9539-c53bec72c2ba.png)

### まとめ

* `delay()`と`SerialUSB`をコメントにして6時間テストしたが問題なかった。
* 割り込みハンドラ内で`delay()`は使うべきではない。（※1）
* 割り込みハンドラ内で`SerialUSB`は使えないと思う。（※1）
* ※1を実現するときはRTOS（FreeRTOSなど）を使って関数を遅延実行するのが一般的。

**Comment by snippet2021** [comment]
> delay()とSerialUSBをコメントにして6時間テストしたが問題なかった。

お手数お掛けして申し訳ありません，ありがとうございます．

> 割り込みハンドラ内でdelay()は使うべきではない。（※1）

申し訳ありません，delay関数は意図せず混入していました．
（今回requestEvent()側は動作させていないことから直接影響は与えていなかったと考えています，）

> 割り込みハンドラ内でSerialUSBは使えないと思う。（※1）

https://github.com/SeeedJP/Arduino_Core_STM32/blob/9e4a250f559fa2e8330aea497e00fe05eb697c82/libraries/Wire/examples/slave_sender_receiver/slave_sender_receiver.ino

内のサンプルコードでコールバックにSerialを使用していたため，SerialUSBも使用可能と考えていましたが，
挙動からしてSerialUSBがloop関数とコールバック関数に両方ある時に再現するため，SerialUSBをコールバック内で使用しないようにします．
（実際wioの代わりにESP32をスレーブとして扱う場合はSerialを呼び出しても正常に動作していました．）

その上で，別のプログラムでSerialUSBを呼んでいない時にも数週間単位で実行して停止することがあったため，上の構成（USBSerialを消したもの）で再現することがあれば改めてisuueをopenさせていただきたく思います．
